version: 0.1

phases:
  build:
    commands:
      - apt-get update
      - apt-get -y install git curl
      - apt-get -y install wget
      - wget https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
      - dpkg -i erlang-solutions_1.0_all.deb
      - apt-get update
      - apt-get install -y erlang
      - apt-get install -y elixir
      - git rev-parse --abbrev-ref HEAD
      - mix local.hex --force
      - mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
      - mix local.rebar --force
      - echo Build started on `date` in dir `pwd`
      - mix deps.get
      - mix test
      - MIX_ENV=prod mix release
  post_build:
    commands:
      - echo Build completed on `date`
      - cp ./_build/prod/rel/sms_rest/releases/*/sms_rest.tar.gz .
      - mkdir temp
      - tar -zxvf sms_rest.tar.gz -C temp
      - cp -r script temp/.
      - cp appspec.yml temp/.
      - bash -c '(cd temp/ && tar -zcvf ../sms_rest.tar.gz *)'
      - bash -c 'mv sms_rest{,-$(git describe --tags || git rev-parse HEAD)}.tar.gz'
      - ls -lrt *.tar.gz
artifacts:
  files:
    - sms_rest*.tar.gz
  discard-paths: yes
